/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamAvailabilityRouteImport } from './routes/team-availability'
import { Route as SprintCalendarRouteImport } from './routes/sprint-calendar'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as AiLogRouteImport } from './routes/ai-log'
import { Route as IndexRouteImport } from './routes/index'

const TeamAvailabilityRoute = TeamAvailabilityRouteImport.update({
  id: '/team-availability',
  path: '/team-availability',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintCalendarRoute = SprintCalendarRouteImport.update({
  id: '/sprint-calendar',
  path: '/sprint-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLogRoute = AiLogRouteImport.update({
  id: '/ai-log',
  path: '/ai-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-log': typeof AiLogRoute
  '/backlog': typeof BacklogRoute
  '/issues': typeof IssuesRoute
  '/settings': typeof SettingsRoute
  '/sprint-calendar': typeof SprintCalendarRoute
  '/team-availability': typeof TeamAvailabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-log': typeof AiLogRoute
  '/backlog': typeof BacklogRoute
  '/issues': typeof IssuesRoute
  '/settings': typeof SettingsRoute
  '/sprint-calendar': typeof SprintCalendarRoute
  '/team-availability': typeof TeamAvailabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-log': typeof AiLogRoute
  '/backlog': typeof BacklogRoute
  '/issues': typeof IssuesRoute
  '/settings': typeof SettingsRoute
  '/sprint-calendar': typeof SprintCalendarRoute
  '/team-availability': typeof TeamAvailabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-log'
    | '/backlog'
    | '/issues'
    | '/settings'
    | '/sprint-calendar'
    | '/team-availability'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-log'
    | '/backlog'
    | '/issues'
    | '/settings'
    | '/sprint-calendar'
    | '/team-availability'
  id:
    | '__root__'
    | '/'
    | '/ai-log'
    | '/backlog'
    | '/issues'
    | '/settings'
    | '/sprint-calendar'
    | '/team-availability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiLogRoute: typeof AiLogRoute
  BacklogRoute: typeof BacklogRoute
  IssuesRoute: typeof IssuesRoute
  SettingsRoute: typeof SettingsRoute
  SprintCalendarRoute: typeof SprintCalendarRoute
  TeamAvailabilityRoute: typeof TeamAvailabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team-availability': {
      id: '/team-availability'
      path: '/team-availability'
      fullPath: '/team-availability'
      preLoaderRoute: typeof TeamAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprint-calendar': {
      id: '/sprint-calendar'
      path: '/sprint-calendar'
      fullPath: '/sprint-calendar'
      preLoaderRoute: typeof SprintCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-log': {
      id: '/ai-log'
      path: '/ai-log'
      fullPath: '/ai-log'
      preLoaderRoute: typeof AiLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiLogRoute: AiLogRoute,
  BacklogRoute: BacklogRoute,
  IssuesRoute: IssuesRoute,
  SettingsRoute: SettingsRoute,
  SprintCalendarRoute: SprintCalendarRoute,
  TeamAvailabilityRoute: TeamAvailabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
